# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_auto_20170322_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='lesson',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date du dernier cours'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='frequency',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Daily'), (7, 'Weekly'), (14, 'Biweekly')], default=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date du premier cours'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Heure du cours'),
            preserve_default=False,
        ),
    ]
