# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_auto_20170417_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='activity',
            field=models.IntegerField(choices=[(0, 'Cascade de glace'), (1, 'Escalade'), (2, 'Freeride'), (3, 'Haute montagne'), (4, 'Rando raquette'), (5, 'Rando ski'), (6, 'Via ferrata')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Debutant'), (1, 'Intermediaire'), (2, 'Experimenté')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='frequency',
            field=models.IntegerField(choices=[(0, 'Une fois'), (1, 'Tous les jours'), (7, 'Toute les semaines'), (14, 'Toute les deux semaines')]),
        ),
    ]
