# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_auto_20170418_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6, verbose_name='Prix'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='activity',
            field=models.IntegerField(choices=[(0, 'Cascade de glace'), (1, 'Escalade'), (2, 'Freeride'), (3, 'Haute montagne'), (4, 'Rando raquette'), (5, 'Rando ski'), (6, 'Via ferrata')], verbose_name='Activité'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Debutant'), (1, 'Intermediaire'), (2, 'Experimenté')], verbose_name='Difficulté'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='frequency',
            field=models.IntegerField(choices=[(0, 'Une fois'), (1, 'Tous les jours'), (7, 'Toute les semaines'), (14, 'Toute les deux semaines')], verbose_name='Fréquence'),
        ),
    ]
