# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_auto_20170322_1411'),
        ('users', '0004_user_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribed_lessons',
            field=models.ManyToManyField(to='lessons.Lesson'),
        ),
    ]
