# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 12:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170415_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpg', upload_to='avatars', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être sous la forme '9999999999' ou '0041999999999'", regex='^\\+?1?\\d{10,13}$')], verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribed_lessons',
            field=models.ManyToManyField(related_name='subscribed_lessons', to='lessons.Lesson'),
        ),
    ]
